# Generated by Django 5.2.3 on 2025-06-27 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OBSPApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('assigned', 'Assigned to Project'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('pitch', models.TextField(help_text="Freelancer's proposal/pitch for this project")),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for Talintz team')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if applicable')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='OBSPAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Assignment'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('review', 'Under Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('freelancer_payout', models.DecimalField(decimal_places=2, help_text='Amount to be paid to freelancer', max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, help_text='Platform commission', max_digits=10)),
                ('milestone_progress', models.JSONField(default=dict, help_text='Progress tracking for each milestone')),
                ('client_feedback', models.TextField(blank=True)),
                ('freelancer_notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Notes for Talintz team')),
                ('quality_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('deadline_met', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='OBSPCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('min_completed_projects', models.PositiveIntegerField(default=2, help_text='Minimum completed projects required')),
                ('min_avg_rating', models.FloatField(default=4.0, help_text='Minimum average rating required')),
                ('min_skill_match_percentage', models.FloatField(default=60.0, help_text='Minimum skill match percentage')),
                ('required_skills', models.JSONField(default=list, help_text='List of required skills')),
                ('core_skills', models.JSONField(default=list, help_text='Core skills that must be present')),
                ('optional_skills', models.JSONField(default=list, help_text='Optional skills that add bonus points')),
                ('min_project_budget', models.DecimalField(decimal_places=2, default=0, help_text='Minimum project budget experience', max_digits=10)),
                ('required_domains', models.JSONField(default=list, help_text='Required project domains')),
                ('min_project_duration_days', models.PositiveIntegerField(default=7, help_text='Minimum project duration experience')),
                ('min_obsp_completed', models.PositiveIntegerField(default=0, help_text='Minimum OBSPs completed at previous level')),
                ('min_deadline_compliance', models.FloatField(default=80.0, help_text='Minimum deadline compliance percentage')),
                ('scoring_weights', models.JSONField(default=dict, help_text='Weights for different scoring components')),
                ('bonus_criteria', models.JSONField(default=dict, help_text='Bonus points criteria')),
                ('penalty_criteria', models.JSONField(default=dict, help_text='Penalty criteria')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['template', 'level'],
            },
        ),
        migrations.CreateModel(
            name='OBSPField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Text Area'), ('number', 'Number Input'), ('email', 'Email Input'), ('phone', 'Phone Input'), ('date', 'Date Input'), ('radio', 'Radio Buttons'), ('checkbox', 'Checkboxes'), ('select', 'Dropdown Select'), ('file', 'File Upload')], max_length=20)),
                ('label', models.CharField(max_length=255)),
                ('placeholder', models.CharField(blank=True, help_text='Placeholder text for input fields', max_length=255)),
                ('help_text', models.CharField(blank=True, help_text='Help text to guide users', max_length=500)),
                ('is_required', models.BooleanField(default=False)),
                ('has_price_impact', models.BooleanField(default=False)),
                ('price_impact', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('options', models.JSONField(default=list, help_text='Options for radio/checkbox/select fields')),
                ('visibility_rule', models.CharField(choices=[('generic', 'Generic - All Levels'), ('low', 'Low Level Only'), ('mid', 'Mid Level Only'), ('high', 'High Level Only'), ('lmid', 'Low + Mid Levels'), ('mhigh', 'Mid + High Levels'), ('low_mid', 'Low + Mid Levels'), ('mid_high', 'Mid + High Levels')], default='generic', help_text='Which levels can see this field', max_length=20)),
                ('phase', models.CharField(choices=[('basic', 'Basic Info - Tell us about your business'), ('core_features', 'Core Features - Choose your essential features'), ('add_ons', 'Add-ons - Enhance your package'), ('review', 'Review & Purchase - Finalize your order')], default='basic', help_text='Which phase/step this field belongs to', max_length=20)),
            ],
            options={
                'ordering': ['template', 'phase', 'order'],
            },
        ),
        migrations.CreateModel(
            name='OBSPLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('name', models.CharField(help_text="Display name for this level (e.g., 'Basic E-commerce')", max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('duration', models.CharField(help_text="Delivery timeline (e.g., '2-3 weeks')", max_length=50)),
                ('features', models.JSONField(default=list, help_text='List of features included in this level')),
                ('deliverables', models.JSONField(default=list, help_text='List of deliverables for this level')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (1=first, 2=second, etc.)')),
            ],
            options={
                'ordering': ['template', 'order'],
            },
        ),
        migrations.CreateModel(
            name='OBSPMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_type', models.CharField(choices=[('requirement_review', 'Requirement Review'), ('design_approval', 'Design Approval'), ('development_progress', 'Development Progress'), ('testing_qa', 'Testing & QA'), ('final_delivery', 'Final Delivery'), ('post_launch', 'Post-Launch Support')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('estimated_days', models.PositiveIntegerField(help_text='Estimated days from project start')),
                ('payout_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of total payment released', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('deliverables', models.JSONField(default=list, help_text='What client receives at this milestone')),
                ('quality_checklist', models.JSONField(default=list, help_text='QA checklist for this milestone')),
                ('client_approval_required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('approved', 'Approved'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['template', 'level', 'order'],
            },
        ),
        migrations.CreateModel(
            name='OBSPResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20, null=True)),
                ('responses', models.JSONField(default=dict, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='draft', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OBSPTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('industry', models.CharField(choices=[('tech', 'Technology'), ('creativity', 'Creativity')], max_length=100)),
                ('description', models.TextField()),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
