# Generated by Django 5.1.6 on 2025-06-27 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OBSP', '0001_initial'),
        ('core', '0001_initial'),
        ('freelancer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='obspapplication',
            name='eligibility_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='freelancer.freelancerobspeligibility'),
        ),
        migrations.AddField(
            model_name='obspapplication',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obsp_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='obspapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obsp_applications_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='obspassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obsp_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='obspassignment',
            name='assigned_freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obsp_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='obspmilestone',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_milestones', to='OBSP.obsplevel'),
        ),
        migrations.AddField(
            model_name='obspassignment',
            name='current_milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OBSP.obspmilestone'),
        ),
        migrations.AddField(
            model_name='obspresponse',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obsp_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='obspassignment',
            name='obsp_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='OBSP.obspresponse'),
        ),
        migrations.AddField(
            model_name='obsptemplate',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
        migrations.AddField(
            model_name='obsptemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='obspresponse',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='OBSP.obsptemplate'),
        ),
        migrations.AddField(
            model_name='obspmilestone',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_milestones', to='OBSP.obsptemplate'),
        ),
        migrations.AddField(
            model_name='obsplevel',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='OBSP.obsptemplate'),
        ),
        migrations.AddField(
            model_name='obspfield',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='OBSP.obsptemplate'),
        ),
        migrations.AddField(
            model_name='obspcriteria',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='OBSP.obsptemplate'),
        ),
        migrations.AddField(
            model_name='obspapplication',
            name='obsp_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='OBSP.obsptemplate'),
        ),
        migrations.AddIndex(
            model_name='obspassignment',
            index=models.Index(fields=['status', 'assigned_freelancer'], name='OBSP_obspas_status_928a28_idx'),
        ),
        migrations.AddIndex(
            model_name='obspassignment',
            index=models.Index(fields=['assigned_at'], name='OBSP_obspas_assigne_99006b_idx'),
        ),
        migrations.AddIndex(
            model_name='obspassignment',
            index=models.Index(fields=['obsp_response', 'status'], name='OBSP_obspas_obsp_re_b19f03_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='obspassignment',
            unique_together={('obsp_response', 'assigned_freelancer')},
        ),
        migrations.AlterUniqueTogether(
            name='obspresponse',
            unique_together={('template', 'client', 'selected_level', 'status')},
        ),
        migrations.AlterUniqueTogether(
            name='obspmilestone',
            unique_together={('template', 'level', 'milestone_type')},
        ),
        migrations.AlterUniqueTogether(
            name='obsplevel',
            unique_together={('template', 'level')},
        ),
        migrations.AddIndex(
            model_name='obspcriteria',
            index=models.Index(fields=['template', 'level'], name='OBSP_obspcr_templat_3e9845_idx'),
        ),
        migrations.AddIndex(
            model_name='obspcriteria',
            index=models.Index(fields=['is_active'], name='OBSP_obspcr_is_acti_49b1cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='obspcriteria',
            unique_together={('template', 'level')},
        ),
        migrations.AddIndex(
            model_name='obspapplication',
            index=models.Index(fields=['status', 'applied_at'], name='OBSP_obspap_status_dcd358_idx'),
        ),
        migrations.AddIndex(
            model_name='obspapplication',
            index=models.Index(fields=['freelancer', 'status'], name='OBSP_obspap_freelan_320abe_idx'),
        ),
        migrations.AddIndex(
            model_name='obspapplication',
            index=models.Index(fields=['obsp_template', 'status'], name='OBSP_obspap_obsp_te_46bfc2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='obspapplication',
            unique_together={('freelancer', 'obsp_template', 'selected_level')},
        ),
    ]
