# Generated by Django 5.1.6 on 2025-07-06 07:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBSP', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obspassignment',
            name='client_feedback',
        ),
        migrations.RemoveField(
            model_name='obspassignment',
            name='freelancer_notes',
        ),
        migrations.RemoveField(
            model_name='obspassignment',
            name='internal_notes',
        ),
        migrations.CreateModel(
            name='OBSPAssignmentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('client_feedback', 'Client Feedback'), ('freelancer_note', 'Freelancer Note'), ('internal_note', 'Internal Note'), ('milestone_feedback', 'Milestone Feedback'), ('quality_review', 'Quality Review'), ('deadline_update', 'Deadline Update')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_private', models.BooleanField(default=False, help_text='Internal notes only visible to admins')),
                ('milestone_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('approved', 'Approved'), ('delivered', 'Delivered')], max_length=20)),
                ('quality_rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='OBSP.obspassignment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OBSP.obspmilestone')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assignment', 'note_type'], name='OBSP_obspas_assignm_0a8fee_idx'), models.Index(fields=['milestone', 'note_type'], name='OBSP_obspas_milesto_6a3d18_idx'), models.Index(fields=['created_at'], name='OBSP_obspas_created_975988_idx')],
            },
        ),
    ]
