# Generated by Django 5.1.6 on 2025-07-06 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OBSP', '0004_obspassignmenthistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OBSPAssignmentHistory',
        ),
    ]
