# Generated by Django 5.1.6 on 2025-07-07 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBSP', '0006_obspassignmenthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obspassignment',
            name='current_milestone',
        ),
        migrations.RemoveField(
            model_name='obspassignment',
            name='milestone_progress',
        ),
        migrations.AddField(
            model_name='obspresponse',
            name='current_milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OBSP.obspmilestone'),
        ),
        migrations.AddField(
            model_name='obspresponse',
            name='milestone_progress',
            field=models.JSONField(default=dict, help_text='Progress tracking for each milestone'),
        ),
    ]
