# Generated by Django 5.1.6 on 2025-07-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBSP', '0007_remove_obspassignment_current_milestone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obspassignmentnote',
            name='is_aknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
