# Generated by Django 5.1.6 on 2025-07-07 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBSP', '0008_obspassignmentnote_is_aknowledged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obspassignmentnote',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='OBSP.obspresponse'),
        ),
    ]
