# Generated by Django 5.1.6 on 2025-07-07 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBSP', '0009_alter_obspassignmentnote_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='obspassignmentnote',
            name='OBSP_obspas_assignm_0a8fee_idx',
        ),
        migrations.RenameField(
            model_name='obspassignmentnote',
            old_name='assignment',
            new_name='response',
        ),
        migrations.AddIndex(
            model_name='obspassignmentnote',
            index=models.Index(fields=['response', 'note_type'], name='OBSP_obspas_respons_1709c3_idx'),
        ),
    ]
