# Generated by Django 5.1.6 on 2025-07-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBSP', '0010_remove_obspassignmentnote_obsp_obspas_assignm_0a8fee_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obsplevel',
            name='max_revisions',
            field=models.PositiveIntegerField(default=2, help_text='Maximum number of revisions allowed for this level'),
        ),
        migrations.AddField(
            model_name='obspresponse',
            name='max_revisions',
            field=models.PositiveIntegerField(blank=True, help_text='Override max revisions for this order (default from level)', null=True),
        ),
    ]
