# Generated by Django 5.1.6 on 2025-07-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBSP', '0012_remove_obspcriteria_core_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obspmilestone',
            name='is_automated',
            field=models.BooleanField(default=True),
        ),
    ]
