# Generated by Django 5.1.6 on 2025-07-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_model_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
