# Generated by Django 5.1.6 on 2025-07-07 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification_related_model_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='object_id',
        ),
    ]
