# Generated by Django 5.1.6 on 2025-07-07 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_notification_object_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMilestoneNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('client_feedback', 'Client Feedback'), ('freelancer_note', 'Freelancer Note'), ('internal_note', 'Internal Note'), ('milestone_feedback', 'Milestone Feedback')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_private', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.milestone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
