# Generated by Django 5.1.6 on 2025-07-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_projectmilestonenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmilestonenote',
            name='is_aknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
