# Generated by Django 5.1.6 on 2025-07-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_projectmilestonenote_is_aknowledged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('approved', 'Approved'), ('delivered', 'Delivered'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
