# Generated by Django 5.1.6 on 2025-07-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_milestone_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='invitation_type',
            field=models.CharField(choices=[('project_assignment', 'Project Assignment'), ('obsp_invitation', 'OBSP Invitation'), ('bid_invitation', 'Bid Invitation'), ('interview_request', 'Interview Request'), ('collaboration_invite', 'Collaboration Invite'), ('connection_request', 'Connection Request'), ('milestone_review', 'Milestone Review'), ('payment_approval', 'Payment Approval')], max_length=30),
        ),
    ]
