# Generated by Django 5.1.6 on 2025-07-06 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBSP', '0006_obspassignmenthistory'),
        ('financeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='obsp_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='OBSP.obspassignment'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='obsp_milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='OBSP.obspmilestone'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='obsp_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='OBSP.obspresponse'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(choices=[('project', 'Project Payment'), ('milestone', 'Milestone Payment'), ('task', 'Task Payment'), ('obsp', 'OBSP Payment'), ('withdrawal', 'Withdrawal'), ('refund', 'Refund'), ('subscription', 'Subscription Payment'), ('deposit', 'Wallet Deposit'), ('escrow', 'Escrow Payment'), ('commission', 'Commission')], max_length=20),
        ),
    ]
