# Generated by Django 5.1.6 on 2025-07-07 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OBSP', '0006_obspassignmenthistory'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_project_start_date'),
        ('financeapp', '0002_transaction_obsp_assignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='workspace/attachments/')),
                ('link', models.URLField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='workspace.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField()),
                ('deadline_passed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='open', max_length=20)),
                ('freelancer_response', models.TextField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.milestone')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='workspace.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_object_id', models.PositiveIntegerField(null=True)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('predefined', 'Predefined'), ('adhoc', 'Ad-hoc')], default='adhoc', max_length=20)),
                ('revision_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('open', 'Open'), ('addressed', 'Addressed'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('addressed_at', models.DateTimeField(blank=True, null=True)),
                ('milestone_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='workspace.workspace')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('client', 'Client'), ('freelancer', 'Freelancer'), ('admin', 'Admin')], max_length=20)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='workspace.workspace')),
            ],
            options={
                'unique_together': {('workspace', 'user')},
            },
        ),
        migrations.CreateModel(
            name='WorkspaceActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('milestone_created', 'Milestone Created'), ('milestone_started', 'Milestone Started'), ('milestone_completed', 'Milestone Completed'), ('milestone_approved', 'Milestone Approved'), ('milestone_rejected', 'Milestone Rejected'), ('milestone_updated', 'Milestone Updated'), ('payment_initiated', 'Payment Initiated'), ('payment_completed', 'Payment Completed'), ('payment_failed', 'Payment Failed'), ('payment_refunded', 'Payment Refunded'), ('file_uploaded', 'File Uploaded'), ('file_downloaded', 'File Downloaded'), ('file_deleted', 'File Deleted'), ('revision_requested', 'Revision Requested'), ('revision_submitted', 'Revision Submitted'), ('revision_approved', 'Revision Approved'), ('revision_rejected', 'Revision Rejected'), ('dispute_raised', 'Dispute Raised'), ('dispute_resolved', 'Dispute Resolved'), ('dispute_escalated', 'Dispute Escalated'), ('meeting_scheduled', 'Meeting Scheduled'), ('meeting_started', 'Meeting Started'), ('meeting_completed', 'Meeting Completed'), ('meeting_cancelled', 'Meeting Cancelled'), ('message_sent', 'Message Sent'), ('note_added', 'Note Added'), ('feedback_given', 'Feedback Given'), ('status_changed', 'Status Changed'), ('deadline_updated', 'Deadline Updated'), ('budget_updated', 'Budget Updated'), ('participant_joined', 'Participant Joined'), ('participant_left', 'Participant Left'), ('role_changed', 'Role Changed')], db_index=True, max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('old_value', models.CharField(blank=True, max_length=100)),
                ('new_value', models.CharField(blank=True, max_length=100)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.milestone')),
                ('obsp_milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OBSP.obspmilestone')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_activities', to='financeapp.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='workspace.workspace')),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspace.workspaceattachment')),
                ('dispute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspace.workspacedispute')),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspace.workspacerevision')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['workspace', 'timestamp'], name='workspace_w_workspa_050ee5_idx'), models.Index(fields=['workspace', 'activity_type'], name='workspace_w_workspa_1fabfa_idx'), models.Index(fields=['workspace', 'user'], name='workspace_w_workspa_96c4dd_idx'), models.Index(fields=['activity_type', 'timestamp'], name='workspace_w_activit_7da1e8_idx'), models.Index(fields=['user', 'timestamp'], name='workspace_w_user_id_f82613_idx')],
            },
        ),
    ]
