# Generated by Django 5.1.6 on 2025-07-09 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="A descriptive title for this box, e.g., 'Milestone 1 Submission'", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description or instructions for this box', null=True)),
                ('object_id', models.PositiveIntegerField(help_text='The ID of the related object (e.g., Milestone ID)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachments', models.ManyToManyField(blank=True, help_text='Attachments included in this box', related_name='boxes', to='workspace.workspaceattachment')),
                ('content_type', models.ForeignKey(help_text='The type of object this box relates to (e.g., Milestone)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='workspace.workspace')),
            ],
        ),
    ]
