# Generated by Django 5.1.6 on 2025-07-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_workspacebox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceactivity',
            name='activity_type',
            field=models.CharField(choices=[('milestone_created', 'Milestone Created'), ('milestone_started', 'Milestone Started'), ('milestone_completed', 'Milestone Completed'), ('milestone_approved', 'Milestone Approved'), ('milestone_rejected', 'Milestone Rejected'), ('milestone_updated', 'Milestone Updated'), ('payment_initiated', 'Payment Initiated'), ('payment_completed', 'Payment Completed'), ('payment_failed', 'Payment Failed'), ('payment_refunded', 'Payment Refunded'), ('file_uploaded', 'File Uploaded'), ('file_downloaded', 'File Downloaded'), ('file_deleted', 'File Deleted'), ('box_uploaded', 'Box Uploaded'), ('box_downloaded', 'Box Downloaded'), ('box_deleted', 'Box Deleted'), ('revision_requested', 'Revision Requested'), ('revision_submitted', 'Revision Submitted'), ('revision_approved', 'Revision Approved'), ('revision_rejected', 'Revision Rejected'), ('dispute_raised', 'Dispute Raised'), ('dispute_resolved', 'Dispute Resolved'), ('dispute_escalated', 'Dispute Escalated'), ('meeting_scheduled', 'Meeting Scheduled'), ('meeting_started', 'Meeting Started'), ('meeting_completed', 'Meeting Completed'), ('meeting_cancelled', 'Meeting Cancelled'), ('message_sent', 'Message Sent'), ('note_added', 'Note Added'), ('feedback_given', 'Feedback Given'), ('status_changed', 'Status Changed'), ('deadline_updated', 'Deadline Updated'), ('budget_updated', 'Budget Updated'), ('participant_joined', 'Participant Joined'), ('participant_left', 'Participant Left'), ('role_changed', 'Role Changed')], db_index=True, max_length=30),
        ),
    ]
