# Generated by Django 5.1.6 on 2025-07-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_alter_workspaceactivity_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacebox',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('viewed', 'Viewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=50),
        ),
    ]
