# Generated by Django 5.1.6 on 2025-07-09 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workspace', '0004_workspacebox_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceactivity',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='workspaceactivity',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
